server:
  port: 10086
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200000000
      max-request-size: 200000000
  mvc:
    view:
      prefix : classpath:/templates
      suffix : .html