server:
  port: 10000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200000000
      max-request-size: 200000000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/event?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
