server:
  port: 10000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200000000
      max-request-size: 200000000
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/gis_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/gis_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/gis_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**
logging:
  file: my.log   # 要制定日志所记录的范围
  level:
    root: info