server:
  port: 10000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200000000
      max-request-size: 200000000
  datasource:
    master:
      url: jdbc:mysql://192.168.223.130:3306/glodon?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      url: jdbc:mysql://192.168.223.131:3306/glodon?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      url: jdbc:mysql://192.168.223.133:3306/glodon?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**
logging:
  file: my.log   #要制定日志所记录的范围
  level:
    root: info
sharding: